import { spawn, type ChildProcess } from 'node:child_process'

const rawArgs = process.argv.slice(2)
const sandboxMode = rawArgs.includes('--sandbox')
const viteArgs = rawArgs.filter((arg) => arg !== '--sandbox')
const children: ChildProcess[] = []
let shuttingDown = false

async function localDevVars() {
  try {
    return await Bun.file('.dev.vars').text()
  } catch {
    return ''
  }
}

function hasLocalDevVar(content: string, name: string, expected?: string) {
  const pattern = new RegExp(`^${name}=([^\\n\\r]*)`, 'm')
  const value = content.match(pattern)?.[1]?.trim()
  if (expected === undefined) return Boolean(value)
  return value === expected
}

async function generatedDevVarsFile(content: string) {
  const lines: string[] = []
  const cloudflareApiToken = process.env.CLOUDFLARE_API_TOKEN?.trim()

  if (cloudflareApiToken && !hasLocalDevVar(content, 'CLOUDFLARE_AI_GATEWAY_TOKEN')) {
    lines.push(`CLOUDFLARE_AI_GATEWAY_TOKEN=${cloudflareApiToken}`)
  }

  if (lines.length === 0) return null

  await Bun.$`mkdir -p .wrangler`
  const filePath = '.wrangler/dev.generated.vars'
  await Bun.write(filePath, [
    '# Generated by scripts/dev.ts. Do not commit.',
    ...lines,
    '',
  ].join('\n'))

  return filePath
}

function start(name: string, command: string, args: string[], env = process.env) {
  const child = spawn(command, args, {
    cwd: process.cwd(),
    env,
    stdio: 'inherit',
  })

  children.push(child)

  child.on('exit', (code, signal) => {
    if (shuttingDown) return
    shuttingDown = true
    const reason = signal ? `${name} stopped with ${signal}` : `${name} exited with ${code ?? 0}`
    console.error(reason)
    stopChildren()
    process.exit(code ?? 1)
  })
}

function stopChildren() {
  for (const child of children) {
    if (!child.killed) child.kill('SIGTERM')
  }
}

process.on('SIGINT', () => {
  shuttingDown = true
  stopChildren()
  process.exit(0)
})

process.on('SIGTERM', () => {
  shuttingDown = true
  stopChildren()
  process.exit(0)
})

const devVars = await localDevVars()
const generatedDevVars = await generatedDevVarsFile(devVars)
if (sandboxMode) {
  const sandboxLabeled = process.env.SYNCFY_ENV === 'sandbox' || hasLocalDevVar(devVars, 'SYNCFY_ENV', 'sandbox')
  const hasSyncfyKey = Boolean(process.env.SYNCFY_API_KEY) || hasLocalDevVar(devVars, 'SYNCFY_API_KEY')

  if (!sandboxLabeled || !hasSyncfyKey) {
    console.error(
      'Sandbox dev requires .dev.vars with SYNCFY_ENV=sandbox and SYNCFY_API_KEY set to the Syncfy sandbox key. See .dev.vars.example.'
    )
    process.exit(1)
  }
}

const workerArgs = ['wrangler', 'dev', '--port', '8788']
if (sandboxMode) {
  workerArgs.push(
    '--env',
    'sandbox',
    '--env-file',
    '.dev.vars'
  )
}
if (generatedDevVars) {
  workerArgs.push('--env-file', generatedDevVars)
}

start('worker', 'bunx', workerArgs)
start('web', 'bunx', ['vite', '--host', '127.0.0.1', ...viteArgs])
